services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=event_user
      - POSTGRES_PASSWORD=event_password
      - POSTGRES_DB=event_ingestion
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nats:
    image: nats:2.10-alpine
    command: --jetstream -m 8222
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  postgres_data: